// ゲームの中身が使う数値を tuning から 1 か所で読む。bot のシミュレーションでも同じものを使う。
import { tune } from '../core/tuning';

export function readParams() {
  return {
    pieceSet: tune<string>('piece.set'),
    maxLanterns: tune('lantern.max'),
    ammoPerHouse: tune('lantern.perHouse'),
    regenTime: tune('lantern.regen'),
    flySpeed: tune('lantern.speed'),
    fuse: tune('lantern.fuse'),
    houseHp: tune('house.hp'),
    fixedHouse: tune('aim.fixed'),
    moveSet: tune('ghost.moves'),
    diagSlope: tune('ghost.diag'),
    catchR: tune('lantern.catch'),
    grabR: tune('lantern.grab'),
    queueGap: tune('ghost.queue'),
    lastRush: tune('ghost.last'),
    chainDelay: tune('chain.delay'),
    dashR: tune('ghost.dashR'),
    dashMult: tune('ghost.dash'),
    chainGrow: tune('chain.grow'),
    chainPad: tune('chain.pad'),
    lureR: tune('lantern.lure'),
    netMult: tune('score.net'),
    reachGrow: tune('light.dayGrow'),
    carryBonus: tune('house.carry'),
    feverAt: tune('fever.at'),
    feverDur: tune('fever.dur'),
    feverMult: tune('fever.mult'),
    day1Speed: tune('ghost.day1'),
    feverEvery: tune('fever.every'),
    feverFromHour: tune('fever.fromHour'),
    lureSpeed: tune('lantern.lureSpeed'),
    sideSpeed: tune('ghost.side'),
    inazumaSpeed: tune('ghost.inazuma'),
    zigLen: tune('ghost.zigLen'),
    kazeSpeed: tune('ghost.kaze'),
    marchDrop: tune('ghost.march'),
    lineReach: tune('light.line'),
    lightWidth: tune('light.width'),
    areaReach: tune('light.area'),
    lightSpeed: tune('light.speed'),
    lightHold: tune('light.hold'),
    relightAt: tune('chain.relightAt'),
    basePts: tune('score.base'),
    ghostSpeed: tune('ghost.speed'),
    loopR: tune('ghost.loop'),
    bigHp: tune('ghost.bigHp'),
    bigPts: tune('score.big'),
    giantHp: tune('ghost.giantHp'),
    giantPts: tune('score.giant'),
    megaHp: tune('ghost.megaHp'),
    megaPts: tune('score.mega'),
    waveBonus: tune('wave.bonus'),
    chainBonus: tune('score.chain'),
    formBonus: tune('score.formation'),
  };
}
export type Params = ReturnType<typeof readParams>;
